FROM sugonhub/sothisai:jupyterlab as base
#请确保网络畅通,除centos7外，其他OS源都无法保证正常使用
#暂不支持python2,原始镜像内python不要安装在某个用户家目录下
#请将以下FROM后的镜像修改为需要添加jupyter的原始镜像
FROM original_images_name
#如有疑问请通过以下邮箱联系
LABEL maintainer="chenwch1@sugon.com"
LABEL module="jupyter"
ENV SHELL=/bin/bash \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8
ARG SOURCES="-i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn"
SHELL ["/bin/bash","-c"]
USER root
RUN set -xe; \
    mkdir /etc/yum.repos.d/bak; \
    mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/bak/; \
    flag="$(cat /etc/redhat-release)"; \
    major_version=$(echo ${flag##*release} | awk '{print $1}' | awk -F. '{print $1}'); \
    release_version=$(echo ${flag##*release} | awk '{print $1}'); \
    minorver=${release_version}; \
    if [[ ${major_version} -lt 7 ]]; \
    then cp /etc/yum.repos.d/bak/CentOS*-Base* /etc/yum.repos.d/; \
    sed -e "s|^mirrorlist=|#mirrorlist=|g" \
         -e "s|^#baseurl=http://mirror.centos.org/centos/\$releasever|baseurl=https://mirrors.aliyun.com/centos-vault/$minorver|g" \
         -i.bak \
         /etc/yum.repos.d/CentOS-*.repo; \
    elif [[ ${major_version} -eq 7 ]]; \
    then curl -ko /etc/yum.repos.d/CentOS-Base.repo https://mirrors.163.com/.help/CentOS7-Base-163.repo; \
    else cp /etc/yum.repos.d/bak/CentOS*-Base* /etc/yum.repos.d/; \
    sed -e "s|^mirrorlist=|#mirrorlist=|g" \
    -e "s|^#baseurl=http://mirror.centos.org/\$contentdir/\$releasever|baseurl=https://mirrors.aliyun.com/centos-vault/$minorver|g" \
    -i.bak \
    /etc/yum.repos.d/CentOS-*.repo;fi; \
    # yum clean all \
    # && yum makecache \
    # && yum install -y \
    # epel-release \
    yum clean all \
    && yum makecache \
    && yum install -y \
    vim \
    which \
    openssl \
    openssl-devel \
    openssl-static \
    net-tools \
    wget \
    git \
    sudo \
    openssh \
    openssh-server \
    && yum clean all \
    && rm -rf /var/cache/yum/*; \
# which python3 2> /dev/null; \
# if [[ $? -ne 0 ]]; \
# then yum makecache \
# && yum install -y \
# python3 \
# python3-pip \
# && yum clean all \
# && rm -rf /var/cache/yum/*;fi; \
rm -rf /etc/yum.repos.d/*.repo \ 
&& mv /etc/yum.repos.d/bak/* /etc/yum.repos.d/ \
&& rm -rf /etc/yum.repos.d/bak; \
pip3 install --upgrade pip ${SOURCES} || pip install --upgrade pip ${SOURCES}; \
pip3 install --no-cache-dir setuptools ${SOURCES} || pip install --no-cache-dir setuptools ${SOURCES}; \
python_version=$(python3 -V | awk '{print $2}' | awk -F. '{print $1$2}'); \
if [[ ${python_version} -lt 35 ]]; \
then pip3 install --no-cache-dir jupyterlab==0.33.12 ${SOURCES} || pip install --no-cache-dir jupyterlab==0.33.12 ${SOURCES}; \
elif [[ ${python_version} -ge 35 && ${python_version} -lt 37 ]]; \
then pip3 install --no-cache-dir jupyterlab==2.3.2 ${SOURCES} || pip install --no-cache-dir jupyterlab==2.3.2 ${SOURCES}; \
else pip3 install --no-cache-dir jupyterlab==3.5.0 ${SOURCES} || pip install --no-cache-dir jupyterlab==3.5.0 ${SOURCES};fi; \
pip3 install --no-cache-dir ipywidgets ${SOURCES} || pip install --no-cache-dir ipywidgets ${SOURCES}
COPY --from=base /tmp/jupyter_lab_config.py /etc/
RUN jupytersite="$(python3 -m pip show jupyterlab | grep -i '^location' | awk '{print $2}')" \
    && JUPYTERLAB_DIR=$(echo ${jupytersite%%/lib/python*}) \
    && if [[ ${JUPYTERLAB_DIR}/bin/jupyter != "/opt/conda/bin/jupyter" ]]; \
    then mkdir -p /opt/conda/bin; \
    ln -sf ${JUPYTERLAB_DIR}/bin/jupyter /opt/conda/bin/jupyter;fi \
    && echo "export JUPYTER_CONFIG_PATH=/etc" >> /etc/bash.bashrc \
    && echo "export JUPYTER=${JUPYTERLAB_DIR}/bin/jupyter" >> /etc/bash.bashrc\
    && echo "export PATH=${JUPYTERLAB_DIR}/bin:${PATH}" >> /etc/bash.bashrc \
    && ssh-keygen  -A \
    && sed -i "s/#UseDNS .*/UseDNS no/" /etc/ssh/sshd_config
EXPOSE 8888